{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b52cb07-d18e-4e32-b1a2-229bc29b2dbd",
   "metadata": {},
   "outputs": [],
   "source": [
    "\\\\Exception handling-1\\\\\n",
    "Ans 1 = An error is an issue in a program that prevents the program from completing its task. In comparison, an exception is a \n",
    "condition that interrupts the normal flow of the program.Both errors and exceptions are a type of runtime error, which\n",
    "means they occur during the execution of a program.\n",
    "\n",
    "Ans 2 = if you don't handle exceptions\n",
    "When an exception occurred, if you don't handle it, the program terminates abruptly and the code past the line that \n",
    "caused the exception will not get executed.\n",
    "\\\\program\\\\\n",
    "try:\n",
    "    fh = open(\"test1.txt\", \"r\")\n",
    "    fh.write(\"This is my test file for exception handling\")\n",
    "except IOError:\n",
    "    print (\"Error: can\\'t find file or read data\")\n",
    "else:\n",
    "    print (\"Written content in the file successfully\")\n",
    "\\\\output\\\\\n",
    "Error: can't find file or read data\n",
    "    \n",
    "Ans 3 = The try and except block in Python is used to\n",
    "catch and handle exceptions. Python executes code following the try statement as a “normal” part of the program.\n",
    "\\\\program \\\\\n",
    "try:\n",
    "    \n",
    "    even_numbers = [2,4,6,8]\n",
    "    print(even_numbers[5])\n",
    "\n",
    "except ZeroDivisionError:\n",
    "    print(\"Denominator cannot be 0.\")\n",
    "    \n",
    "except IndexError:\n",
    "    print(\"Index Out of Bound.\")\n",
    "\n",
    "    \\\\output\\\\\n",
    "Index Out of Bound. \n",
    "\n",
    "Ans 4 = \n",
    "a} try and else \n",
    "# program to print the reciprocal of even numbers\n",
    "\n",
    "try:\n",
    "    num = int(input(\"Enter a number: \"))\n",
    "    assert num % 2 == 0\n",
    "except:\n",
    "    print(\"Not an even number!\")\n",
    "else:\n",
    "    reciprocal = 1/num\n",
    "    print(reciprocal)\n",
    "\\\\output\\\\    \n",
    "Enter a number:  56\n",
    "0.017857142857142856\n",
    "\n",
    "b} finally \n",
    "\\\\program\\\\\n",
    "try:\n",
    "  x > 3\n",
    "except:\n",
    "  print(\"Something went wrong\")\n",
    "else:\n",
    "  print(\"Nothing went wrong\")\n",
    "finally:\n",
    "  print(\"The try...except block is finished\")\n",
    "\\\\output\\\\\n",
    "Something went wrong\n",
    "The try...except block is finished\n",
    "\n",
    "c} raise \n",
    "\\\\program\\\\\n",
    "#Raise an error and stop the program if x is lower than 0:\n",
    "x = -1\n",
    "\n",
    "if x < 0:\n",
    "    raise Exception(\"Sorry, no numbers below zero\")\n",
    "\\\\output\\\\\n",
    "Exception                                 Traceback (most recent call last)\n",
    "Cell In[14], line 5\n",
    "      2 x = -1\n",
    "      4 if x < 0:\n",
    "----> 5     raise Exception(\"Sorry, no numbers below zero\")\n",
    "\n",
    "Exception: Sorry, no numbers below zero\n",
    "\n",
    "\n",
    "Ans 5 = \n",
    "Built-in exceptions offer information about Python-related problems, and custom exceptions will add information about \n",
    "project-related problems. That way, you can design your code (and traceback, if an exception is raised) in a way that \n",
    "combines Python code with the language of the project\n",
    "\\\\ program of custome exception \\\\\n",
    "class CustomException(Exception):\n",
    "    \"\"\" my custom exception class \"\"\"\n",
    "\n",
    "\n",
    "try:\n",
    "    raise CustomException('This is my custom exception')\n",
    "except CustomException as ex:\n",
    "    print(ex)\n",
    "\\\\output\\\\\n",
    "This is my custom exception\n",
    "\n",
    "\n",
    "Ans 6 = \n",
    "# define Python user-defined exceptions\n",
    "class InvalidAgeException(Exception):\n",
    "    \"Raised when the input value is less than 18\"\n",
    "    pass\n",
    "\n",
    "# you need to guess this number\n",
    "number = 18\n",
    "\n",
    "try:\n",
    "    input_num = int(input(\"Enter a number: \"))\n",
    "    if input_num < number:\n",
    "        raise InvalidAgeException\n",
    "    else:\n",
    "        print(\"Eligible to Vote\")\n",
    "        \n",
    "except InvalidAgeException:\n",
    "    print(\"Exception occurred: Invalid Age\")\n",
    "\\\\output\\\\\n",
    "Enter a number:  12\n",
    "Exception occurred: Invalid Age\n",
    "or \n",
    "Enter a number:  45\n",
    "Eligible to Vote"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
